version: '3'
services:
    judge_server:
        image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
        container_name: gp_judger
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - $PWD/server/judge:/code:ro
            - $PWD/docker_data/judge/judgefile:/test_case:ro
            - $PWD/docker_data/judge/log:/log
            - $PWD/docker_data/judge/run:/judger
        environment:
            - BACKEND_URL=http://backend:80/api/judge_server_heartbeat
            - SERVICE_URL=http://judge-server:12358
            - TOKEN=shu
        ports:
            - 0.0.0.0:12358:8080


    # redis:
    #     image: redis 
    #     container_name: gp-redis
    #     command: redis-server --requirepass 12345678
    #     # restart: always
    #     ports:
    #         - 6380:6379  

    # mysql:
    #     image: mysql
    #     container_name: gp-mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 12345678
    #     volumes:
    #         - ./docker_data/mysql/data:/var/lib/mysql
    #         - ./docker_data/mysql/my.cnf:/etc/my.cnf
    #         - ./docker_data/mysql/init:/docker-entrypoint-initdb.d/
    #     ports:
    #         - 3307:3306

    file:
        build:
            context : ./
            dockerfile : ./docker/file/Dockerfile
        container_name: gp-file
        restart: always
        ports:
            - 8082:8082
        volumes:
            - $PWD/docker_data/judge/judgefile:/go/src/github.com/qinhan-shu/gp-server/docker_data/judge/judgefile
        environment:
            REDIS_ADDR: 172.19.154.222:6379  
            REDIS_PASS: 12345678
            REDIS_POOLSIZE: 10
            MYSQL_ADDR: 172.19.154.222:3306
            MYSQL_USER: root
            MYSQL_PASS: 12345678
            MYSQL_DBNAME: gp_oj
            MYSQL_OPEN_CONNS_NUM: 100
            MYSQL_IDLE_CONNS_NUM: 100
            JUDGE_SERVER: gp_judger:8080+shu
            LOG_LEVEL: debug
            MAXUPLOADSIZE: 2
            WEB_PORT: :8081
            FILE_PORT: :8082
            CERTFILE: ""
            KEYFILE: ""

    web:
        build:
            context : ./
            dockerfile : ./docker/web/Dockerfile
        container_name: gp-web
        restart: always
        ports:
            - 8081:8081
        environment:
            REDIS_ADDR:  172.19.154.222:6379  
            REDIS_PASS: 12345678
            REDIS_POOLSIZE: 10
            MYSQL_ADDR:  172.19.154.222:3306
            MYSQL_USER: root
            MYSQL_PASS: 12345678
            MYSQL_DBNAME: gp_oj
            MYSQL_OPEN_CONNS_NUM: 100
            MYSQL_IDLE_CONNS_NUM: 100
            JUDGE_SERVER: gp_judger:8080+shu
            LOG_LEVEL: debug
            MAXUPLOADSIZE: 2
            WEB_PORT: :8081
            FILE_PORT: :8082
            CERTFILE: ""
            KEYFILE: ""
        depends_on:
            # - mysql
            # - redis
            - file
            - judge_server
    
