version: '3'
services:
    mysql:
        image: mysql
        container_name: gp-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/my.cnf:/etc/my.cnf
            - ./config/init:/docker-entrypoint-initdb.d/
        ports:
            - 3306

    redis:
        image: redis 
        container_name: gp-redis
        command: redis-server --requirepass 12345678
        # restart: always
        ports:
            - 6379   

    judge_server:
        image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
        container_name: judger
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - $PWD/judgefile:/test_case:ro
            - $PWD/log:/log
            - $PWD/server/judge:/code:ro
            - $PWD/run:/judger
        environment:
            - BACKEND_URL=http://backend:80/api/judge_server_heartbeat
            - SERVICE_URL=http://judge-server:12358
            - TOKEN=shu
        ports:
            - 8081


    web:
        build:
            context : ./
            dockerfile : ./docker/web/Dockerfile
        container_name: gp-web
        restart: always
        ports:
            - 8080:8080
        environment:
            REDIS_ADDR: gp-redis:6379  
            REDIS_PASS: 12345678
            REDIS_POOLSIZE: 10
            MYSQL_ADDR: gp-mysql:3306
            MYSQL_USER: root
            MYSQL_PASS: 12345678
            MYSQL_DBNAME: gp_oj
            MYSQL_OPEN_CONNS_NUM: 100
            MYSQL_IDLE_CONNS_NUM: 100
            JUDGE_SERVER: judger:8081+shu
        depends_on:
            - mysql
            - redis
            - judge_server