version: '3'
services:
  web:
    build:
        context : ./
        dockerfile : ./docker/web/Dockerfile
    ports:
        - 8080:8080
    environment:
        GITHUB_USERNAME: ${USERNAME}
        GITHUB_TOKEN: ${TOKEN}
        GITHUB_URL: ${URL}
